server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 20M;

    # React Router — барлық беттерді index.html-ге бағыттау
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip сығу
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;
}
